import "./globals.css";
import {Montserrat} from "next/font/google";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ['400','700'],
    variable: '--font-Montserrat'
})
export const metadata = {
    title: 'TestLand',
    description: 'Generated by create next app',
    icon: '/favicon.ico'
};

export default function RootLayout({ children }) {
    return (
        <html lang= 'en'>
        <body className = {`${montserrat.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}